apiVersion: v1
kind: Service
metadata:
  name: mokaform-backend
  labels:
    app: mokaform-backend
spec:
  type: ClusterIP
  selector:
    app: mokaform-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
